/** Studio's text (Studio-Dashboard, Studio-Wizard, Studio-Checkin boards and the undrawn screens). */
import type { Dict } from '../copy';

export const STUDIO = {
  title: { en: 'FeestFinder for organisers', vi: 'FeestFinder cho nhà tổ chức' },
  studio: { en: 'Studio', vi: 'Studio' },
  nav: { en: 'Studio', vi: 'Studio' },
  publicProfile: { en: 'View public profile', vi: 'Xem hồ sơ công khai' },
  newEvent: { en: 'New event', vi: 'Sự kiện mới' },
  dash: { en: 'Dashboard', vi: 'Bảng điều khiển' },
  attendees: { en: 'Attendees', vi: 'Người tham dự' },
  door: { en: 'Check-in', vi: 'Check-in' },
  revenue: { en: 'Revenue', vi: 'Doanh thu' },
  inbox: { en: 'Inbox', vi: 'Hộp thư' },
  announce: { en: 'Announcements', vi: 'Thông báo' },
  promos: { en: 'Promos & guests', vi: 'Mã giảm giá & khách mời' },
  gigs: { en: 'Gigs & bookings', vi: 'Gig & booking' },
  business: { en: 'Business details', vi: 'Thông tin doanh nghiệp' },
  signOut: { en: 'Log out', vi: 'Đăng xuất' },
  gate: { en: 'Log in to list and manage your events', vi: 'Đăng nhập để đăng và quản lý sự kiện' },
  signIn: { en: 'Log in', vi: 'Đăng nhập' },
  notOrg: { en: 'This account has no organiser profile yet', vi: 'Tài khoản này chưa có hồ sơ nhà tổ chức' },
  becomeOrg: { en: 'Create an organiser profile', vi: 'Tạo hồ sơ nhà tổ chức' },
  pickEvent: { en: 'Event', vi: 'Sự kiện' },
  noEvents: { en: 'No events yet', vi: 'Chưa có sự kiện nào' },
  viewPage: { en: 'View page', vi: 'Xem trang' },
  range: { en: 'Range', vi: 'Khoảng thời gian' },
  days: { en: '{n} days', vi: '{n} ngày' },
  // dashboard
  views: { en: 'Views', vi: 'Lượt xem' },
  saves: { en: 'Saves', vi: 'Lượt lưu' },
  clicks: { en: 'Ticket clicks', vi: 'Lượt bấm mua vé' },
  registerClicks: { en: 'Sign-up clicks', vi: 'Lượt bấm đăng ký' },
  sold: { en: 'Sold', vi: 'Đã bán' },
  registered: { en: 'Signed up', vi: 'Đã đăng ký' },
  ofViews: { en: '{p} of views', vi: '{p} lượt xem' },
  vsBefore: { en: '{d} vs the period before', vi: '{d} so với kỳ trước' },
  noBefore: { en: 'Nothing in the period before', vi: 'Kỳ trước chưa có' },
  viewsPerDay: { en: 'Views per day', vi: 'Lượt xem mỗi ngày' },
  nViews: { en: '{n} views', vi: '{n} lượt xem' },
  pace: { en: 'Selling pace', vi: 'Nhịp bán' },
  daysToDoors: { en: 'days to doors', vi: 'ngày tới giờ mở cửa' },
  needPerDay: { en: 'Needed per day', vi: 'Cần mỗi ngày' },
  ratePerDay: { en: 'Selling per day', vi: 'Đang đạt mỗi ngày' },
  onPace: { en: 'On pace', vi: 'Đúng nhịp' },
  behind: { en: 'Behind', vi: 'Chậm nhịp' },
  boostLine: { en: 'Boost the listing to the Trending shelf for more views.', vi: 'Đẩy tin lên mục Đang hot để kéo lượt xem.' },
  boost: { en: 'Boost listing', vi: 'Đẩy tin' },
  boostAsked: { en: 'Boost requested', vi: 'Đã gửi yêu cầu đẩy tin' },
  boostDone: { en: 'Featured', vi: 'Đang nổi bật' },
  yourEvents: { en: 'Your events', vi: 'Sự kiện của bạn' },
  pickRow: { en: 'Pick a row to see its numbers', vi: 'Bấm một dòng để xem số liệu' },
  colEvent: { en: 'Event', vi: 'Sự kiện' },
  colDate: { en: 'Date', vi: 'Ngày' },
  colStatus: { en: 'Status', vi: 'Trạng thái' },
  colFill: { en: 'Tickets · places', vi: 'Vé · chỗ' },
  draft: { en: 'Draft', vi: 'Nháp' },
  continue: { en: 'Continue', vi: 'Tiếp tục' },
  sources: { en: 'Where views come from', vi: 'Lượt xem đến từ đâu' },
  srcFeed: { en: 'FeestFinder feed', vi: 'Nguồn cấp FeestFinder' },
  srcShelf: { en: 'Trending shelf', vi: 'Mục Đang hot' },
  srcShared: { en: 'Shared links', vi: 'Liên kết chia sẻ' },
  srcSearch: { en: 'Search', vi: 'Tìm kiếm' },
  srcOwn: { en: 'Your own links', vi: 'Liên kết của bạn' },
  srcAds: { en: 'Ads', vi: 'Quảng cáo' },
  srcMap: { en: 'Map', vi: 'Bản đồ' },
  srcList: { en: 'List', vi: 'Danh sách' },
  srcArtist: { en: 'Artist profiles', vi: 'Hồ sơ nghệ sĩ' },
  todo: { en: 'To do', vi: 'Việc cần làm' },
  noNumbers: { en: 'Numbers show once the event is live', vi: 'Số liệu hiện khi sự kiện đã đăng' },
  // wizard
  wTitle: { en: 'List an event', vi: 'Đăng sự kiện' },
  wNew: { en: 'New event', vi: 'Sự kiện mới' },
  wEdit: { en: 'Edit event', vi: 'Sửa sự kiện' },
  wDraft: { en: 'Draft · autosaved', vi: 'Nháp · tự lưu' },
  wSaving: { en: 'Saving…', vi: 'Đang lưu…' },
  wSaved: { en: 'Saved {t}', vi: 'Đã lưu {t}' },
  wNotSaved: { en: 'Not saved: {m}', vi: 'Chưa lưu được: {m}' },
  wClose: { en: 'Close, the draft is saved', vi: 'Đóng, nháp đã được lưu' },
  wDone: { en: '{n} / 3 required parts', vi: '{n} / 3 phần bắt buộc' },
  wNext: { en: 'Continue', vi: 'Tiếp tục' },
  s1: { en: 'Basics', vi: 'Cơ bản' },
  s2: { en: 'Time & place', vi: 'Thời gian & địa điểm' },
  s3: { en: 'Tickets', vi: 'Vé' },
  s4: { en: 'Review & submit', vi: 'Xem lại & gửi duyệt' },
  fName: { en: 'Event name', vi: 'Tên sự kiện' },
  fNamePh: { en: 'e.g. White Night Open Air', vi: 'vd: Đêm Trắng Open Air' },
  fGenre: { en: 'Genre', vi: 'Thể loại' },
  fDesc: { en: 'Description', vi: 'Mô tả' },
  fDescPh: { en: 'Line-up, doors, what to know before you come', vi: 'Line-up, giờ mở cửa, lưu ý khi đến' },
  optional: { en: '· optional', vi: '· không bắt buộc' },
  fLineup: { en: 'Line-up', vi: 'Dàn nghệ sĩ' },
  fLineupPh: { en: 'Add an artist, press Enter', vi: 'Thêm nghệ sĩ, bấm Enter' },
  fRemoveArtist: { en: 'Remove {n}', vi: 'Bỏ {n}' },
  fLogo: { en: 'Logo', vi: 'Logo' },
  fLogoHint: { en: 'Square, 256 × 256 or larger', vi: 'Vuông, từ 256 × 256' },
  fCover: { en: 'Cover', vi: 'Ảnh bìa' },
  fCoverHint: { en: '1600 × 900. Left empty, the genre\'s shapes are the cover.', vi: '1600 × 900. Bỏ trống thì dùng bìa hình khối theo thể loại.' },
  fUpload: { en: 'Upload', vi: 'Tải lên' },
  fChange: { en: 'Change', vi: 'Đổi' },
  fRemove: { en: 'Remove', vi: 'Xoá' },
  fUploading: { en: 'Uploading…', vi: 'Đang tải lên…' },
  fEventUrl: { en: 'Event page', vi: 'Trang sự kiện' },
  fEventUrlPh: { en: 'https://facebook.com/events/…', vi: 'https://facebook.com/events/…' },
  fUrlRule: { en: 'Links start with https://', vi: 'Link bắt đầu bằng https://' },
  fDate: { en: 'Date', vi: 'Ngày' },
  fDoors: { en: 'Doors', vi: 'Mở cửa' },
  fEnd: { en: 'Ends', vi: 'Kết thúc' },
  fVenue: { en: 'Venue', vi: 'Địa điểm' },
  fVenuePh: { en: 'Venue name or address', vi: 'Tên địa điểm hoặc địa chỉ' },
  fVenueNew: { en: 'New venue: checked in review', vi: 'Địa điểm mới: được kiểm tra khi duyệt' },
  fRecent: { en: 'Recent:', vi: 'Gần đây:' },
  fCity: { en: 'City', vi: 'Thành phố' },
  fAge: { en: 'Age', vi: 'Độ tuổi' },
  allAges: { en: 'All ages', vi: 'Mọi lứa tuổi' },
  fMode: { en: 'Entry', vi: 'Hình thức' },
  paid: { en: 'Tickets', vi: 'Bán vé' },
  free: { en: 'Free', vi: 'Miễn phí' },
  fPrice: { en: 'Price from ({c})', vi: 'Giá từ ({c})' },
  fTicketUrl: { en: 'Ticket link', vi: 'Link bán vé' },
  fTicketNote: { en: 'Buyers go to your ticket seller. FeestFinder charges no booking fee.', vi: 'Người mua được chuyển sang đơn vị bán vé. FeestFinder không thu phí đặt vé.' },
  fSellHere: { en: 'Sell on FeestFinder', vi: 'Bán vé trên FeestFinder' },
  fSellNote: { en: 'Buyers pay here; the ticket link takes over when tiers sell out.', vi: 'Người mua thanh toán tại FeestFinder; hết hạng vé thì dùng link bán vé.' },
  tier: { en: 'Tier', vi: 'Hạng vé' },
  tierPrice: { en: 'Price ({c})', vi: 'Giá ({c})' },
  tierQty: { en: 'Tickets', vi: 'Số vé' },
  tierNamePh: { en: 'e.g. General', vi: 'vd: Phổ thông' },
  tierName: { en: 'Tier name', vi: 'Tên hạng vé' },
  tierRemove: { en: 'Remove tier', vi: 'Xoá hạng vé' },
  tierSold: { en: '{n} sold', vi: 'đã bán {n}' },
  addTier: { en: 'Add a tier', vi: 'Thêm hạng vé' },
  fRegister: { en: 'Sign-up required', vi: 'Cần đăng ký trước' },
  fRegisterUrl: { en: 'Sign-up link', vi: 'Link đăng ký' },
  missingHead: { en: 'Missing before you can submit', vi: 'Còn thiếu trước khi gửi' },
  mTitle: { en: 'Event name', vi: 'Tên sự kiện' },
  mGenre: { en: 'Genre', vi: 'Thể loại' },
  mLogo: { en: 'Logo', vi: 'Logo' },
  mEventUrl: { en: 'Event page', vi: 'Trang sự kiện' },
  mDates: { en: 'Date, doors and end', vi: 'Ngày, giờ mở cửa và kết thúc' },
  mVenue: { en: 'Venue', vi: 'Địa điểm' },
  mPrice: { en: 'Price and ticket link', vi: 'Giá và link bán vé' },
  agree: { en: 'The details are right and I have the right to run this event.', vi: 'Thông tin chính xác và tôi có quyền tổ chức sự kiện này.' },
  submit: { en: 'Submit for review', vi: 'Gửi duyệt' },
  submitNote: { en: 'Usually reviewed within about 2 hours.', vi: 'Thường được duyệt trong khoảng 2 giờ.' },
  resubmit: { en: 'Save and send for review again', vi: 'Lưu và gửi duyệt lại' },
  sent: { en: 'Submitted', vi: 'Đã gửi duyệt' },
  sentLine: { en: '{t} goes live on FeestFinder once it is approved.', vi: '{t} sẽ lên FeestFinder sau khi được duyệt.' },
  sentNote: { en: 'You get an email and a message in the Inbox.', vi: 'Bạn sẽ nhận email và thông báo trong Hộp thư.' },
  boostOffer: { en: 'Put it on the Trending shelf once it is live', vi: 'Đưa lên mục Đang hot khi tin được duyệt' },
  backToDash: { en: 'Back to the dashboard', vi: 'Về bảng điều khiển' },
  listAnother: { en: 'List another event', vi: 'Đăng sự kiện khác' },
  preview: { en: 'Preview in the feed', vi: 'Xem trước trong feed' },
  justListed: { en: 'Just listed', vi: 'Mới đăng' },
  noDate: { en: 'No date yet', vi: 'Chưa chọn ngày' },
  noTitle: { en: 'Event name', vi: 'Tên sự kiện' },
  sentBack: { en: 'Sent back: {r}', vi: 'Bị trả lại: {r}' },
  liveEdit: { en: 'Changes to the date, venue, price or cover send the listing back to review.', vi: 'Sửa ngày, địa điểm, giá hay ảnh bìa thì tin sẽ được duyệt lại.' },
  saveChanges: { en: 'Save changes', vi: 'Lưu thay đổi' },
  notEditable: { en: 'This listing can no longer be edited', vi: 'Tin này không còn sửa được' },
  // check-in
  backToStudio: { en: 'Back to Studio', vi: 'Về Studio' },
  online: { en: 'Online', vi: 'Trực tuyến' },
  offline: { en: 'Offline · {n} to sync', vi: 'Ngoại tuyến · {n} chờ đồng bộ' },
  offlineNone: { en: 'Offline', vi: 'Ngoại tuyến' },
  sync: { en: 'Sync', vi: 'Đồng bộ' },
  syncing: { en: 'Syncing…', vi: 'Đang đồng bộ…' },
  notSynced: { en: 'Not synced yet: the scans are still on this device', vi: 'Chưa đồng bộ được: lượt quét vẫn nằm trên máy' },
  gatePick: { en: 'Gate', vi: 'Cổng' },
  gateMain: { en: 'Main', vi: 'Cổng chính' },
  gateVip: { en: 'VIP', vi: 'VIP' },
  gateSide: { en: 'Side', vi: 'Cổng phụ' },
  viewfinder: { en: 'QR scanner', vi: 'Khung quét mã QR' },
  aim: { en: 'Hold the QR code in the frame', vi: 'Đưa mã QR vào khung' },
  camera: { en: 'Use the camera', vi: 'Bật camera' },
  cameraOff: { en: 'Stop the camera', vi: 'Tắt camera' },
  cameraBlocked: { en: 'The camera is blocked. Type the code instead.', vi: 'Không mở được camera. Hãy nhập mã vé.' },
  code: { en: 'Ticket code', vi: 'Mã vé' },
  codePh: { en: 'Type the ticket code', vi: 'Nhập mã vé' },
  check: { en: 'Check', vi: 'Kiểm tra' },
  codeShort: { en: 'Scan the QR or type the code on the ticket', vi: 'Quét QR hoặc nhập mã trên vé' },
  rValid: { en: 'Valid', vi: 'Hợp lệ' },
  rUsed: { en: 'Already used', vi: 'Đã dùng' },
  rInvalid: { en: 'Not valid', vi: 'Không hợp lệ' },
  inside: { en: '/ {n} in', vi: '/ {n} đã vào' },
  perHour: { en: '{n} an hour', vi: '{n} người / giờ' },
  recentScans: { en: 'Just scanned', vi: 'Vừa quét' },
  noScans: { en: 'No scans yet', vi: 'Chưa có lượt quét' },
  queued: { en: 'on this device', vi: 'trên máy' },
  crew: { en: 'Door staff', vi: 'Nhân sự cửa' },
  crewAdd: { en: 'Add a scanner', vi: 'Thêm người soát vé' },
  crewName: { en: 'Full name', vi: 'Họ tên' },
  crewPhone: { en: 'Phone number', vi: 'Số điện thoại' },
  crewRole: { en: 'Access', vi: 'Quyền' },
  crewScanner: { en: 'Scanner', vi: 'Soát vé' },
  crewLead: { en: 'Gate lead', vi: 'Trưởng cửa' },
  crewSend: { en: 'Send invite', vi: 'Gửi lời mời' },
  crewInvited: { en: 'Invited', vi: 'Chờ nhận' },
  crewOn: { en: 'Scanning', vi: 'Đang soát' },
  crewOff: { en: 'Paused', vi: 'Tạm ngưng' },
  crewScans: { en: '{n} scans', vi: '{n} lượt quét' },
  crewPause: { en: 'Pause', vi: 'Tạm ngưng' },
  crewResume: { en: 'Resume', vi: 'Cho soát tiếp' },
  crewRemove: { en: 'Remove {n}', vi: 'Xoá {n}' },
  crewActive: { en: '{n} scanning now', vi: '{n} người đang soát' },
  cancel: { en: 'Cancel', vi: 'Huỷ' },
  noEvent: { en: 'Pick an event with tickets to check in', vi: 'Chọn một sự kiện có vé để soát' },
  // shared
  saved: { en: 'Saved', vi: 'Đã lưu' },
  save: { en: 'Save', vi: 'Lưu' },
  add: { en: 'Add', vi: 'Thêm' },
  remove: { en: 'Remove', vi: 'Xoá' },
  loadMore: { en: 'Show more', vi: 'Xem thêm' },
  search: { en: 'Search', vi: 'Tìm' },
  pickAnEvent: { en: 'Pick an event to see this', vi: 'Chọn một sự kiện để xem mục này' },
  confirm: { en: 'Confirm', vi: 'Xác nhận' },
  // attendees
  attSold: { en: 'Tickets out', vi: 'Vé đã phát' },
  attIn: { en: 'Checked in', vi: 'Đã check-in' },
  attOut: { en: 'Not in yet', vi: 'Chưa vào' },
  attRefunded: { en: 'Refunded', vi: 'Đã hoàn tiền' },
  attOfCap: { en: 'of {n} places', vi: 'trên {n} chỗ' },
  attPctSold: { en: '{p} of tickets out', vi: '{p} số vé' },
  fAll: { en: 'All', vi: 'Tất cả' },
  fIn: { en: 'Checked in', vi: 'Đã vào' },
  fOut: { en: 'Not in', vi: 'Chưa vào' },
  fVip: { en: 'VIP', vi: 'VIP' },
  fRefunded: { en: 'Refunded', vi: 'Hoàn tiền' },
  attSearch: { en: 'Name, phone or code', vi: 'Tên, số điện thoại hoặc mã' },
  csv: { en: 'Download CSV', vi: 'Tải CSV' },
  colName: { en: 'Name', vi: 'Họ tên' },
  colPhone: { en: 'Phone', vi: 'Điện thoại' },
  colTier: { en: 'Ticket', vi: 'Hạng vé' },
  colBought: { en: 'Bought', vi: 'Mua' },
  colState: { en: 'Status', vi: 'Trạng thái' },
  stIn: { en: 'In', vi: 'Đã vào' },
  stOut: { en: 'Not in', vi: 'Chưa vào' },
  stRefunded: { en: 'Refunded', vi: 'Đã hoàn' },
  resend: { en: 'Resend ticket', vi: 'Gửi lại vé' },
  refund: { en: 'Refund order', vi: 'Hoàn tiền đơn' },
  refundAsk: { en: 'Refund order {c}? Its tickets stop working.', vi: 'Hoàn tiền đơn {c}? Vé của đơn sẽ hết hiệu lực.' },
  noAttendees: { en: 'No one here yet', vi: 'Chưa có ai' },
  actions: { en: 'Actions for {n}', vi: 'Thao tác cho {n}' },
  // announcements
  annNew: { en: 'New announcement', vi: 'Thông báo mới' },
  annTo: { en: 'To', vi: 'Gửi tới' },
  audSaved: { en: 'Saved it', vi: 'Đã lưu' },
  audHolders: { en: 'Ticket holders', vi: 'Đã mua vé' },
  audVip: { en: 'VIP', vi: 'VIP' },
  audPast: { en: 'Past guests', vi: 'Khách kỳ trước' },
  annChannels: { en: 'Channels', vi: 'Kênh' },
  annReach: { en: 'Reaches {n} of {m}', vi: 'Tới {n} / {m} người' },
  annSubject: { en: 'Subject', vi: 'Tiêu đề' },
  annBody: { en: 'Message', vi: 'Nội dung' },
  annWhen: { en: 'Send', vi: 'Gửi' },
  annNow: { en: 'Now', vi: 'Ngay' },
  annLater: { en: 'Schedule', vi: 'Hẹn giờ' },
  annAt: { en: 'Send at', vi: 'Gửi lúc' },
  annSend: { en: 'Send', vi: 'Gửi' },
  annSchedule: { en: 'Schedule', vi: 'Hẹn gửi' },
  annRule: { en: 'One announcement per event every 24 hours, up to 320 characters.', vi: 'Mỗi sự kiện một thông báo trong 24 giờ, tối đa 320 ký tự.' },
  annSent: { en: 'Sent and scheduled', vi: 'Đã gửi và đã hẹn' },
  annNone: { en: 'Nothing sent yet', vi: 'Chưa gửi thông báo nào' },
  annOpened: { en: '{p}% opened', vi: '{p}% đã mở' },
  annScheduled: { en: 'Scheduled', vi: 'Đã hẹn' },
  annSentSt: { en: 'Sent', vi: 'Đã gửi' },
  annCancel: { en: 'Cancel', vi: 'Huỷ lịch' },
  annPeople: { en: '{n} people', vi: '{n} người' },
  annNotLive: { en: 'Announcements go out once the listing is live', vi: 'Chỉ gửi thông báo khi tin đã lên sóng' },
  // promos and guests
  promoCodes: { en: 'Promo codes', vi: 'Mã giảm giá' },
  promoNew: { en: 'New code', vi: 'Mã mới' },
  promoCode: { en: 'Code', vi: 'Mã' },
  promoPct: { en: 'Discount (%)', vi: 'Giảm (%)' },
  promoCap: { en: 'Uses', vi: 'Số lượt' },
  promoCreate: { en: 'Create code', vi: 'Tạo mã' },
  promoUsed: { en: '{u} / {c} used', vi: 'Đã dùng {u} / {c}' },
  promoOn: { en: '{c} on', vi: 'Bật {c}' },
  promoNone: { en: 'No codes yet', vi: 'Chưa có mã nào' },
  promoStats: { en: '{r} uses · {d} off', vi: '{r} lượt dùng · giảm {d}' },
  promoNearly: { en: 'Nearly used up', vi: 'Sắp hết lượt' },
  guests: { en: 'Guest list', vi: 'Khách mời' },
  guestName: { en: 'Guest name', vi: 'Tên khách' },
  guestSeats: { en: 'Seats', vi: 'Số chỗ' },
  guestAdd: { en: 'Add guest', vi: 'Thêm khách' },
  guestIn: { en: '{n} checked in', vi: 'Đã vào: {n}' },
  guestNone: { en: 'No guests yet', vi: 'Chưa có khách mời' },
  guestRemove: { en: 'Remove {n}', vi: 'Xoá {n}' },
  // revenue
  gross: { en: 'Gross', vi: 'Doanh thu' },
  net: { en: 'Net to you', vi: 'Thực nhận' },
  ticketsSold: { en: 'Tickets sold', vi: 'Vé đã bán' },
  avgTicket: { en: 'Average ticket', vi: 'Giá vé trung bình' },
  refunds: { en: 'Refunds', vi: 'Hoàn tiền' },
  refundLine: { en: '{n} tickets · {p}%', vi: '{n} vé · {p}%' },
  salesPerDay: { en: 'Tickets per day', vi: 'Vé bán mỗi ngày' },
  fullPrice: { en: 'Full price', vi: 'Giá gốc' },
  withCode: { en: 'With a code', vi: 'Dùng mã' },
  byTier: { en: 'By tier', vi: 'Theo hạng vé' },
  fees: { en: 'Fees', vi: 'Phí' },
  payouts: { en: 'Payouts', vi: 'Thanh toán' },
  statement: { en: 'Statement (CSV)', vi: 'Sao kê (CSV)' },
  pPaid: { en: 'Paid', vi: 'Đã chuyển' },
  pAvailable: { en: 'Available', vi: 'Có thể nhận' },
  pScheduled: { en: 'Scheduled', vi: 'Đã lên lịch' },
  pHeld: { en: 'Held', vi: 'Đang giữ' },
  pReleased: { en: 'Released', vi: 'Đã giải phóng' },
  account: { en: 'Payout account', vi: 'Tài khoản nhận tiền' },
  accountAdd: { en: 'Add a bank account', vi: 'Thêm tài khoản ngân hàng' },
  accountChange: { en: 'Change', vi: 'Đổi' },
  bank: { en: 'Bank', vi: 'Ngân hàng' },
  accountNo: { en: 'Account number', vi: 'Số tài khoản' },
  accountName: { en: 'Account holder', vi: 'Chủ tài khoản' },
  verified: { en: 'Verified', vi: 'Đã xác minh' },
  unverified: { en: 'Being checked', vi: 'Đang xác minh' },
  noSales: { en: 'Revenue shows once tickets sell on FeestFinder', vi: 'Doanh thu hiện khi có vé bán qua FeestFinder' },
  // inbox
  messages: { en: 'Messages', vi: 'Tin nhắn' },
  notifications: { en: 'Notifications', vi: 'Thông báo' },
  notifSettings: { en: 'Settings', vi: 'Cài đặt' },
  noThreads: { en: 'No messages', vi: 'Chưa có tin nhắn' },
  reply: { en: 'Reply…', vi: 'Trả lời…' },
  send: { en: 'Send', vi: 'Gửi' },
  readAll: { en: 'Mark all read', vi: 'Đánh dấu đã đọc' },
  noNotifs: { en: 'No notifications', vi: 'Chưa có thông báo' },
  topicModeration: { en: 'Review decisions', vi: 'Kết quả kiểm duyệt' },
  topicTickets: { en: 'Ticket sales', vi: 'Bán vé' },
  topicPayouts: { en: 'Payouts', vi: 'Thanh toán' },
  topicCrew: { en: 'Gate crew', vi: 'Crew cổng' },
  topicBookings: { en: 'Bookings', vi: 'Booking' },
  testPush: { en: 'Send a test notification', vi: 'Gửi thông báo thử' },
  backToList: { en: 'All messages', vi: 'Tất cả tin nhắn' },
  appeal: { en: 'Appeal', vi: 'Khiếu nại' },
  appealPh: { en: 'What should the moderator know?', vi: 'Kiểm duyệt viên cần biết gì?' },
  appealSend: { en: 'Send appeal', vi: 'Gửi khiếu nại' },
  appealSent: { en: 'Appeal sent', vi: 'Đã gửi khiếu nại' },
  // gigs
  gigPosted: { en: 'Your gigs', vi: 'Gig đã đăng' },
  gigNew: { en: 'Post a gig', vi: 'Đăng gig' },
  gigTitle: { en: 'Title', vi: 'Tiêu đề' },
  gigTitlePh: { en: 'e.g. Warm-up DJ, Saturday', vi: 'vd: DJ mở màn tối thứ Bảy' },
  gigDate: { en: 'Date', vi: 'Ngày diễn' },
  gigCloses: { en: 'Applications close', vi: 'Hạn nhận hồ sơ' },
  gigType: { en: 'Kind of gig', vi: 'Loại gig' },
  gigSet: { en: 'Set length', vi: 'Thời lượng set' },
  gigFeeMin: { en: 'Fee from', vi: 'Thù lao từ' },
  gigFeeMax: { en: 'Fee up to', vi: 'Thù lao đến' },
  gigTravel: { en: 'Travel covered', vi: 'Lo chi phí đi lại' },
  gigDesc: { en: 'Details', vi: 'Chi tiết' },
  gigEvent: { en: 'For the event', vi: 'Cho sự kiện' },
  gigNoEvent: { en: 'Not tied to an event', vi: 'Không gắn với sự kiện' },
  gigPost: { en: 'Post gig', vi: 'Đăng gig' },
  gigOpen: { en: 'Open', vi: 'Đang nhận' },
  gigClosed: { en: 'Closed', vi: 'Đã đóng' },
  gigFilled: { en: 'Filled', vi: 'Đã chốt' },
  gigClose: { en: 'Close applications', vi: 'Đóng nhận hồ sơ' },
  gigReopen: { en: 'Reopen', vi: 'Mở lại' },
  gigApps: { en: '{n} applications', vi: '{n} hồ sơ' },
  gigNone: { en: 'No gigs posted', vi: 'Chưa đăng gig nào' },
  appsNone: { en: 'No applications yet', vi: 'Chưa có hồ sơ' },
  shortlist: { en: 'Shortlist', vi: 'Chọn vào danh sách' },
  decline: { en: 'Decline', vi: 'Từ chối' },
  book: { en: 'Book', vi: 'Chốt' },
  appShortlisted: { en: 'Shortlisted', vi: 'Trong danh sách' },
  appDeclined: { en: 'Declined', vi: 'Đã từ chối' },
  appBooked: { en: 'Booked', vi: 'Đã chốt' },
  appNew: { en: 'New', vi: 'Mới' },
  inquiries: { en: 'Booking requests sent', vi: 'Yêu cầu booking đã gửi' },
  inqNone: { en: 'Book an artist from their profile', vi: 'Gửi yêu cầu booking từ hồ sơ nghệ sĩ' },
  inqPending: { en: 'Waiting', vi: 'Chờ trả lời' },
  inqAccepted: { en: 'Accepted', vi: 'Đã nhận' },
  inqDeclined: { en: 'Declined', vi: 'Đã từ chối' },
  // business profile
  bizPublic: { en: 'Public profile', vi: 'Hồ sơ công khai' },
  bizLegal: { en: 'Business and contact', vi: 'Doanh nghiệp và liên hệ' },
  bizTeam: { en: 'Team', vi: 'Thành viên' },
  bizName: { en: 'Organiser name', vi: 'Tên nhà tổ chức' },
  bizType: { en: 'Type', vi: 'Loại hình' },
  bizBio: { en: 'About', vi: 'Giới thiệu' },
  bizWebsite: { en: 'Website', vi: 'Website' },
  bizMarkets: { en: 'Cities', vi: 'Thành phố hoạt động' },
  bizOpen: { en: 'Open to artist submissions', vi: 'Nhận hồ sơ nghệ sĩ' },
  bizLegalName: { en: 'Legal name', vi: 'Tên pháp lý' },
  bizTax: { en: 'Tax code', vi: 'Mã số thuế' },
  bizTaxHint: { en: '10 to 14 digits', vi: '10 đến 14 chữ số' },
  bizAddress: { en: 'Address', vi: 'Địa chỉ' },
  bizEmail: { en: 'Email', vi: 'Email' },
  bizHotline: { en: 'Hotline', vi: 'Hotline' },
  bizZalo: { en: 'Zalo', vi: 'Zalo' },
  bizContact: { en: 'Contact person', vi: 'Người liên hệ' },
  bizRole: { en: 'Their role', vi: 'Chức vụ' },
  bizLinks: { en: 'Links', vi: 'Liên kết' },
  roleOwner: { en: 'Owner', vi: 'Chủ tài khoản' },
  roleMember: { en: 'Member', vi: 'Thành viên' },
  bizVerified: { en: 'Verified organiser', vi: 'Nhà tổ chức đã xác minh' },
  bizUnverified: { en: 'Not verified yet', vi: 'Chưa xác minh' },
} satisfies Dict;
