/** The organiser and artist pages' text; English from the legacy web screen where it had the line. */
import type { Dict } from '../../copy';

export const PROFILE = {
  follow: { en: 'Follow', vi: 'Theo dõi' },
  following: { en: 'Following', vi: 'Đang theo dõi' },
  followed: { en: 'Following {n}', vi: 'Đang theo dõi {n}' },
  unfollowed: { en: 'Unfollowed {n}', vi: 'Đã bỏ theo dõi {n}' },
  followers: { en: 'Followers', vi: 'Người theo dõi' },
  share: { en: 'Share profile', vi: 'Chia sẻ hồ sơ' },
  linkCopied: { en: 'Link copied', vi: 'Đã chép liên kết' },
  edit: { en: 'Edit profile', vi: 'Chỉnh hồ sơ' },
  about: { en: 'About', vi: 'Giới thiệu' },
  more: { en: 'Show more', vi: 'Xem thêm' },
  less: { en: 'Show less', vi: 'Thu gọn' },
  links: { en: 'Links', vi: 'Liên kết' },
  nEvents: { en: '{n} events', vi: '{n} sự kiện' },
  allPast: { en: 'All {n} events', vi: 'Xem toàn bộ {n} sự kiện' },
  verified: { en: 'Verified', vi: 'Đã xác minh' },
  interested: { en: '{n} interested', vi: '{n} quan tâm' },
  events: { en: 'Events', vi: 'Sự kiện' },
  // organiser
  orgKind: { en: 'Organiser', vi: 'Nhà tổ chức' },
  orgVerified: { en: 'Verified organiser', vi: 'Nhà tổ chức đã xác minh' },
  orgEvents: { en: 'Events listed', vi: 'Sự kiện đã đăng' },
  orgArtistsN: { en: 'Artists', vi: 'Nghệ sĩ' },
  since: { en: 'since {y}', vi: 'từ {y}' },
  upcoming: { en: 'Upcoming', vi: 'Sắp tới' },
  past: { en: 'Past', vi: 'Đã tổ chức' },
  noUpcoming: { en: 'Nothing on sale right now. Follow to hear first.', vi: 'Hiện chưa có sự kiện nào. Theo dõi để nhận tin sớm nhất.' },
  families: { en: 'What it runs', vi: 'Thể loại tổ chức' },
  orgArtists: { en: 'Artists it books', vi: 'Nghệ sĩ thường mời' },
  orgVenues: { en: 'Venues it uses', vi: 'Địa điểm thường dùng' },
  business: { en: 'Business details', vi: 'Thông tin doanh nghiệp' },
  businessType: { en: 'Type', vi: 'Loại hình' },
  website: { en: 'Website', vi: 'Website' },
  markets: { en: 'Cities', vi: 'Thành phố' },
  open: { en: 'Open for artist submissions', vi: 'Nhận hồ sơ nghệ sĩ' },
  checked: { en: 'Checked', vi: 'Đã đối chiếu' },
  unchecked: { en: 'Not checked yet', vi: 'Chưa đối chiếu' },
  isThisYouOrg: { en: 'Are you this organiser?', vi: 'Bạn là nhà tổ chức này?' },
  gateClaim: { en: 'Log in to manage this profile', vi: 'Đăng nhập để quản lý hồ sơ này' },
  // artist
  artistKind: { en: 'Artist', vi: 'Nghệ sĩ' },
  artistVerified: { en: 'Verified artist', vi: 'Nghệ sĩ đã xác minh' },
  travel: { en: 'Travels', vi: 'Đi diễn' },
  active: { en: 'Active', vi: 'Hoạt động' },
  shows: { en: 'Upcoming shows', vi: 'Show sắp tới' },
  played: { en: 'Played', vi: 'Đã diễn' },
  cities: { en: 'Cities', vi: 'Thành phố' },
  upcomingTab: { en: 'Upcoming', vi: 'Sắp diễn' },
  pastTab: { en: 'Played', vi: 'Đã diễn' },
  noShows: { en: 'No shows coming up. Follow to hear first.', vi: 'Chưa có show sắp tới. Theo dõi để nhận tin sớm nhất.' },
  nextShow: { en: 'Next', vi: 'Show tới' },
  listen: { en: 'Listen', vi: 'Nghe' },
  workedWith: { en: 'Worked with', vi: 'Đã hợp tác' },
  playedAt: { en: 'Played at', vi: 'Đã diễn tại' },
  sharedLineups: { en: 'Shared lineups', vi: 'Từng diễn chung' },
  similar: { en: 'Similar artists', vi: 'Nghệ sĩ tương tự' },
  gear: { en: 'Gear & software', vi: 'Thiết bị & phần mềm' },
  dates: { en: 'Dates', vi: 'Lịch' },
  free: { en: 'Free', vi: 'Rảnh' },
  busy: { en: 'Busy', vi: 'Bận' },
  booking: { en: 'Booking', vi: 'Booking' },
  gigTypes: { en: 'Plays', vi: 'Nhận diễn' },
  setLengths: { en: 'Set lengths', vi: 'Thời lượng set' },
  languages: { en: 'Languages', vi: 'Ngôn ngữ' },
  brands: { en: 'Open to brand work', vi: 'Nhận hợp tác thương hiệu' },
  details: { en: 'Booking details', vi: 'Thông tin booking' },
  bell: { en: 'Show alerts', vi: 'Báo khi có show' },
  bellOn: { en: 'Alerts on for {n}', vi: 'Sẽ báo khi {n} có show' },
  isThisYouArtist: { en: 'Are you this artist?', vi: 'Bạn là nghệ sĩ này?' },
  mostWith: { en: 'Played most with', vi: 'Diễn nhiều nhất với' },
  orgShows: { en: 'Organiser · {n} shows', vi: 'Nhà tổ chức · {n} show' },
  together: { en: '{n} shows together', vi: '{n} show chung' },
  nShows: { en: '{n} shows', vi: '{n} show' },
  buy: { en: 'Tickets', vi: 'Mua vé' },
  freeEntry: { en: 'Free', vi: 'Miễn phí' },
  soldOut: { en: 'Sold out', vi: 'Hết vé' },
  fromPrice: { en: 'from {p}', vi: 'từ {p}' },
  playedN: { en: 'Played', vi: 'Show đã diễn' },
} satisfies Dict;
