/**
 * The public site's text. English comes from the legacy web screen's logic.js where it had
 * the same line.
 */
import type { Dict } from '../copy';

export const WEB = {
  // frame
  home: { en: 'FeestFinder, home', vi: 'FeestFinder, trang chủ' },
  mainNav: { en: 'Main', vi: 'Chính' },
  explore: { en: 'Explore', vi: 'Khám phá' },
  map: { en: 'Map', vi: 'Bản đồ' },
  genres: { en: 'Genres', vi: 'Thể loại' },
  search: { en: 'Search', vi: 'Tìm kiếm' },
  searchPh: { en: 'Events, artists, venues…', vi: 'Sự kiện, nghệ sĩ, địa điểm…' },
  searchGo: { en: 'Search', vi: 'Tìm' },
  listEvent: { en: 'List your event', vi: 'Đăng sự kiện' },
  account: { en: 'Account', vi: 'Tài khoản' },
  you: { en: 'You', vi: 'Bạn' },
  myProfile: { en: 'My profile', vi: 'Hồ sơ của tôi' },
  myTickets: { en: 'My tickets', vi: 'Vé của tôi' },
  saved: { en: 'Saved', vi: 'Đã lưu' },
  artistSpace: { en: 'Artist workspace', vi: 'Khu nghệ sĩ' },
  orgSpace: { en: 'Organizer workspace', vi: 'Khu nhà tổ chức' },
  roleBecome: { en: 'Artist or organiser?', vi: 'Bạn là nghệ sĩ hay nhà tổ chức?' },
  rolePending: { en: 'Claim waiting for review', vi: 'Yêu cầu đang chờ duyệt' },
  signIn: { en: 'Log in', vi: 'Đăng nhập' },
  signOut: { en: 'Sign out', vi: 'Đăng xuất' },
  close: { en: 'Close', vi: 'Đóng' },
  footerNav: { en: 'Footer', vi: 'Chân trang' },
  forOrganisers: { en: 'For organisers', vi: 'Cho nhà tổ chức' },
  about: { en: 'About', vi: 'Về FeestFinder' },
  advertise: { en: 'Advertise', vi: 'Quảng cáo' },
  company: { en: '© {y} FestFinder Co., Ltd', vi: '© {y} Công ty TNHH FestFinder' },
  crumbs: { en: 'Breadcrumb', vi: 'Đường dẫn' },
  english: { en: 'English', vi: 'English' },
  vietnamese: { en: 'Tiếng Việt', vi: 'Tiếng Việt' },

  // cards
  saveEvent: { en: 'Save {t}', vi: 'Lưu {t}' },
  interested: { en: '{n} interested', vi: '{n} quan tâm' },
  free: { en: 'Free', vi: 'Miễn phí' },
  fromPrice: { en: 'from {p}', vi: 'từ {p}' },
  soldOut: { en: 'Sold out', vi: 'Hết vé' },
  ended: { en: 'Ended', vi: 'Đã kết thúc' },
  featured: { en: 'Featured', vi: 'Nổi bật' },

  // event page
  sectionNav: { en: 'On this page', vi: 'Mục trên trang' },
  tabAbout: { en: 'About', vi: 'Giới thiệu' },
  tabLineup: { en: 'Line-up', vi: 'Line-up' },
  tabTickets: { en: 'Tickets', vi: 'Vé' },
  tabVenue: { en: 'Venue', vi: 'Địa điểm' },
  buyTickets: { en: 'Get tickets', vi: 'Mua vé' },
  chooseTickets: { en: 'Choose tickets · from {p}', vi: 'Chọn vé · từ {p}' },
  freeEntry: { en: 'Free entry', vi: 'Vào cửa miễn phí' },
  daysLeft: { en: 'In {n} days', vi: 'Còn {n} ngày' },
  tomorrow: { en: 'Tomorrow', vi: 'Ngày mai' },
  today: { en: 'Today', vi: 'Hôm nay' },
  onNow: { en: 'On now', vi: 'Đang diễn ra' },
  addCalendar: { en: 'Add to calendar', vi: 'Thêm lịch' },
  directions: { en: 'Directions', vi: 'Chỉ đường' },
  copyAddress: { en: 'Copy address', vi: 'Chép địa chỉ' },
  copied: { en: 'Copied', vi: 'Đã chép' },
  verifiedOrg: { en: 'Verified', vi: 'Đã xác minh' },
  saveThis: { en: 'Save this event', vi: 'Lưu sự kiện' },
  savedThis: { en: 'Saved', vi: 'Đã lưu' },
  share: { en: 'Share', vi: 'Chia sẻ' },
  updates: { en: 'From the organiser', vi: 'Tin từ BTC' },
  about2: { en: 'About', vi: 'Giới thiệu' },
  places: { en: '{n} places', vi: '{n} chỗ' },
  lineup: { en: 'Line-up · {n} artists', vi: 'Line-up · {n} nghệ sĩ' },
  stages: { en: '{n} stages', vi: '{n} sân khấu' },
  headline: { en: 'Headline', vi: 'Headline' },
  byStage: { en: 'Set times by stage', vi: 'Lịch theo sân khấu' },
  planCount: { en: '{n} in your plan', vi: '{n} set trong lịch của bạn' },
  planPick: { en: 'Add {a} to my plan', vi: 'Thêm {a} vào lịch' },
  planDrop: { en: 'Remove {a} from my plan', vi: 'Bỏ {a} khỏi lịch' },
  planClear: { en: 'Clear', vi: 'Bỏ hết' },
  planRemind: { en: 'Remind me 15 min before', vi: 'Nhắc trước 15 phút' },
  planReminded: { en: 'Reminders on', vi: 'Đã đặt nhắc' },
  clashLine: { en: '{a} and {b} overlap by {m} minutes', vi: '{a} và {b} trùng nhau {m} phút' },
  gatePlan: { en: 'Log in to plan your sets', vi: 'Đăng nhập để chọn set' },
  followingArtists: { en: 'Following {n} of this line-up', vi: 'Đang theo dõi {n} nghệ sĩ trong line-up' },
  tickets: { en: 'Tickets', vi: 'Vé' },
  ticketTiers: { en: 'Ticket tiers', vi: 'Hạng vé' },
  tierOnSale: { en: 'On sale', vi: 'Còn vé' },
  tierLast: { en: 'Last tier', vi: 'Hạng cuối' },
  tierFew: { en: 'Few left', vi: 'Còn ít' },
  tierSoldOut: { en: 'Sold out', vi: 'Hết vé' },
  tierSoon: { en: 'Not yet open', vi: 'Chưa mở bán' },
  tierNotify: { en: 'Notify me', vi: 'Nhắc tôi' },
  tierLeft: { en: '{n} left', vi: 'Còn {n}' },
  quantity: { en: 'Quantity', vi: 'Số lượng' },
  qtyLabel: { en: 'Number of tickets', vi: 'Số lượng vé' },
  qtyDec: { en: 'One fewer', vi: 'Bớt một vé' },
  qtyInc: { en: 'One more', vi: 'Thêm một vé' },
  buyN: { en: 'Buy {n} {t} · {p}', vi: 'Mua {n} vé {t} · {p}' },
  soldVia: { en: 'Sold via {h} · up to {n} tickets · no booking fee from FeestFinder', vi: 'Bán qua {h} · tối đa {n} vé · FeestFinder không thu phí đặt vé' },
  soldHere: { en: 'Sold on FeestFinder · up to {n} tickets · no booking fee', vi: 'Bán trên FeestFinder · tối đa {n} vé · không thu phí đặt vé' },
  refund: { en: 'Refunds', vi: 'Hoàn tiền' },
  noTicketLink: { en: 'The organiser has not posted a ticket link yet', vi: 'Nhà tổ chức chưa đăng link bán vé' },
  ticketsAtDoor: { en: 'Tickets', vi: 'Vé' },
  freeNote: { en: 'No ticket needed', vi: 'Không cần vé' },
  eventEnded: { en: 'This event has ended', vi: 'Sự kiện đã kết thúc' },
  resale: { en: 'Resale', vi: 'Pass vé' },
  resaleCap: { en: 'At most face value', vi: 'Không quá giá gốc' },
  resaleNone: { en: 'No tickets up right now', vi: 'Chưa có vé pass' },
  resaleWatch: { en: 'Tell me when one comes up', vi: 'Báo tôi khi có vé' },
  resaleWatching: { en: 'We will tell you', vi: 'Đang chờ báo' },
  resaleBuy: { en: 'Buy', vi: 'Mua' },
  resaleMine: { en: 'Yours', vi: 'Vé của bạn' },
  resaleFace: { en: 'Face value {p}', vi: 'Giá gốc {p}' },
  resaleFee: { en: '+{p}% service fee', vi: '+{p}% phí dịch vụ' },
  resaleSell: { en: 'Pass on your ticket', vi: 'Pass vé của bạn' },
  hype: { en: 'Hype', vi: 'Hype' },
  hypeIt: { en: 'Hype it', vi: 'Hype ngay' },
  hyped: { en: 'Hyped', vi: 'Đã hype' },
  hype24: { en: '+{n} in the last 24h', vi: '+{n} trong 24 giờ qua' },
  hypeLeft: { en: '{n} to go', vi: 'Còn {n}' },
  hypeCount: { en: '{n} hype', vi: '{n} hype' },
  faq: { en: 'Asked & answered', vi: 'Câu hỏi thường gặp' },
  venue: { en: 'Venue', vi: 'Địa điểm' },
  travel: { en: 'Getting there & parking', vi: 'Đi lại & gửi xe' },
  entryRules: { en: 'Entry rules', vi: 'Quy định vào cổng' },
  onMap: { en: 'See on the map', vi: 'Xem trên bản đồ' },
  alsoBy: { en: 'Also by {o}', vi: 'Cũng của {o}' },
  upcoming: { en: 'Upcoming', vi: 'Sắp tới' },
  youMayLike: { en: 'You may also like', vi: 'Có thể bạn thích' },
  viewProfile: { en: 'View profile', vi: 'Xem hồ sơ' },
  report: { en: 'Report this listing', vi: 'Báo cáo tin này' },
  reportWhat: { en: 'What is wrong?', vi: 'Vấn đề là gì?' },
  reportMore: { en: 'Anything else we should know', vi: 'Điều gì khác chúng tôi nên biết' },
  reportSend: { en: 'Send report', vi: 'Gửi báo cáo' },
  reportSent: { en: 'Report sent', vi: 'Đã gửi báo cáo' },
  reported: { en: 'Reported', vi: 'Đã báo cáo' },
  gateReport: { en: 'Log in to report a listing', vi: 'Đăng nhập để báo cáo' },
  sources: { en: 'Sources', vi: 'Nguồn' },
  communityBy: { en: 'Sent in by {n}', vi: '{n} gửi lên' },
  communityBySomeone: { en: 'Sent in by the community', vi: 'Cộng đồng gửi lên' },
  claim: { en: 'I organise this', vi: 'Tôi là BTC' },
  claimPending: { en: 'Claim under review', vi: 'Đang chờ duyệt' },
  claimTitle: { en: 'Take over this event', vi: 'Nhận quản lý sự kiện' },
  claimNote: { en: 'Who you are, and how we can check', vi: 'Bạn là ai, và cách chúng tôi xác minh' },
  claimProof: { en: 'Proof link (page or post)', vi: 'Link chứng minh (fanpage, bài đăng)' },
  claimSend: { en: 'Send request', vi: 'Gửi yêu cầu' },
  claimShort: { en: 'At least 10 characters', vi: 'Ít nhất 10 ký tự' },
  gateClaim: { en: 'Log in to claim this event', vi: 'Đăng nhập để nhận quản lý' },
  // share
  shareCopy: { en: 'Copy link', vi: 'Chép liên kết' },
  shareCopied: { en: 'Link copied', vi: 'Đã chép liên kết' },
  shareCopiedZalo: { en: 'Link copied — paste it into Zalo', vi: 'Đã chép — dán vào Zalo' },
  shareCopiedMessenger: { en: 'Link copied — paste it into Messenger', vi: 'Đã chép — dán vào Messenger' },
  shareStory: { en: 'Story image', vi: 'Ảnh story' },
  shareVideo: { en: 'Short video', vi: 'Video ngắn' },
  storySaved: { en: 'Story image saved', vi: 'Đã lưu ảnh story' },
  videoMaking: { en: 'Making the video…', vi: 'Đang tạo video…' },
  videoReady: { en: 'Share the video', vi: 'Chia sẻ video' },
  videoSaved: { en: 'Video saved — post it on TikTok', vi: 'Đã lưu video — đăng lên TikTok' },
  videoNone: { en: 'This browser can’t make videos — here is the picture', vi: 'Trình duyệt không tạo được video — dùng ảnh thay' },
  shareMore: { en: 'More', vi: 'Khác' },
  collect: { en: 'Add to a collection', vi: 'Thêm vào bộ sưu tập' },
  colNewPh: { en: 'New collection', vi: 'Bộ sưu tập mới' },
  colCreate: { en: 'Create', vi: 'Tạo' },
  colAdded: { en: 'Added to {n}', vi: 'Đã thêm vào {n}' },
  colRemoved: { en: 'Removed from {n}', vi: 'Đã bỏ khỏi {n}' },
  gateCollect: { en: 'Log in to make collections', vi: 'Đăng nhập để tạo bộ sưu tập' },
  // discussion
  discussion: { en: 'Discussion', vi: 'Thảo luận' },
  discTop: { en: 'Helpful', vi: 'Hữu ích' },
  discNew: { en: 'Newest', vi: 'Mới nhất' },
  discPost: { en: 'Post', vi: 'Đăng' },
  discReply: { en: 'Reply', vi: 'Trả lời' },
  discReplyPh: { en: 'Write a reply…', vi: 'Viết trả lời…' },
  discWritePh: { en: 'Write something…', vi: 'Viết gì đó…' },
  discHelpful: { en: 'Helpful', vi: 'Hữu ích' },
  discReport: { en: 'Report', vi: 'Báo cáo' },
  discReported: { en: 'Reported · thanks', vi: 'Đã báo cáo · cảm ơn bạn' },
  discDelete: { en: 'Delete', vi: 'Xoá' },
  discPin: { en: 'Pin', vi: 'Ghim' },
  discUnpin: { en: 'Unpin', vi: 'Bỏ ghim' },
  discHide: { en: 'Hide', vi: 'Ẩn' },
  discShow: { en: 'Show', vi: 'Hiện lại' },
  discPinned: { en: 'Pinned', vi: 'Đã ghim' },
  discOfficial: { en: 'Organiser’s answer', vi: 'BTC trả lời' },
  discHidden: { en: 'Hidden', vi: 'Đang ẩn' },
  discRemoved: { en: 'Deleted', vi: 'Đã xoá' },
  discMore: { en: '{n} more replies', vi: 'Thêm {n} trả lời' },
  discEmpty: { en: 'Nothing here yet', vi: 'Chưa có bài nào' },
  discClosed: { en: 'Closed for new posts', vi: 'Đang đóng' },
  discSignin: { en: 'Log in to post', vi: 'Đăng nhập để đăng bài' },
  discVerify: { en: 'Confirm your phone to post', vi: 'Xác thực SĐT để đăng bài' },
  discMember: { en: 'FeestFinder member', vi: 'Thành viên FeestFinder' },
  discPhoto: { en: 'Photo', vi: 'Ảnh' },
  discHeard: { en: 'Heard at (HH:MM)', vi: 'Nghe lúc (HH:MM)' },
  discSort: { en: 'Order', vi: 'Thứ tự' },
  photos: { en: 'Photo wall', vi: 'Tường ảnh' },
  ambassadors: { en: 'Ambassadors', vi: 'Đại sứ' },
  ambVisits: { en: '{n} visits', vi: '{n} lượt xem' },
  agoMin: { en: '{n} min ago', vi: '{n} phút trước' },
  agoHour: { en: '{n} h ago', vi: '{n} giờ trước' },
  agoDay: { en: '{n} d ago', vi: '{n} ngày trước' },
  justNow: { en: 'just now', vi: 'vừa xong' },
} satisfies Dict;
