/** /saved's text; English from the legacy web screen (pages/web/logic.js) where it had the line. */
import type { Dict } from '../../copy';

export const SAVED = {
  title: { en: 'Saved', vi: 'Đã lưu' },
  gate: { en: 'Log in to keep events here', vi: 'Đăng nhập để lưu sự kiện ở đây' },
  all: { en: 'All saved', vi: 'Tất cả' },
  collections: { en: 'Collections', vi: 'Bộ sưu tập' },
  newShort: { en: 'New', vi: 'Mới' },
  newTitle: { en: 'New collection', vi: 'Bộ sưu tập mới' },
  namePh: { en: 'Collection name', vi: 'Tên bộ sưu tập' },
  create: { en: 'Create', vi: 'Tạo' },
  created: { en: '{n} created', vi: 'Đã tạo {n}' },
  pickTitle: { en: 'Save to a collection', vi: 'Lưu vào bộ sưu tập' },
  collectEvent: { en: 'Add {t} to a collection', vi: 'Lưu {t} vào bộ sưu tập' },
  added: { en: 'Added to {n}', vi: 'Đã thêm vào {n}' },
  removed: { en: 'Removed from {n}', vi: 'Đã bỏ khỏi {n}' },
  isPublic: { en: 'Public', vi: 'Công khai' },
  isPrivate: { en: 'Private', vi: 'Riêng tư' },
  publicLink: { en: 'Public link', vi: 'Link công khai' },
  publicOn: { en: 'Public link on', vi: 'Đã bật link công khai' },
  publicOff: { en: 'Public link off', vi: 'Đã tắt link công khai' },
  share: { en: 'Share', vi: 'Chia sẻ' },
  rename: { en: 'Rename', vi: 'Đổi tên' },
  saveName: { en: 'Save', vi: 'Lưu' },
  cancel: { en: 'Cancel', vi: 'Huỷ' },
  del: { en: 'Delete', vi: 'Xoá' },
  delArm: { en: 'Tap again to delete', vi: 'Bấm lần nữa để xoá' },
  deleted: { en: 'Collection deleted', vi: 'Đã xoá bộ sưu tập' },
  missing: { en: 'Collection not found', vi: 'Không tìm thấy bộ sưu tập' },
  nEvents: { en: '{n} events', vi: '{n} sự kiện' },
  empty: { en: 'Nothing saved yet', vi: 'Chưa lưu sự kiện nào' },
  colEmpty: { en: 'Nothing in this collection yet', vi: 'Bộ sưu tập chưa có sự kiện' },
  explore: { en: 'Explore events', vi: 'Khám phá sự kiện' },
  past: { en: 'Past', vi: 'Đã qua' },
  more: { en: 'Show more', vi: 'Xem thêm' },
  saveThis: { en: 'Save {t}', vi: 'Lưu {t}' },
  kicker: { en: 'Collection', vi: 'Bộ sưu tập' },
} satisfies Dict;
