/** /list's text; English from the legacy web screen where it had the line. */
import type { Dict } from '../../copy';

export const LIST = {
  title: { en: 'Every event', vi: 'Tất cả sự kiện' },
  count: { en: '{n} events', vi: '{n} sự kiện' },
  nearest: { en: '{n} events · nearest first', vi: '{n} sự kiện · gần nhất trước' },
  updated: { en: 'Updated {t}', vi: 'Cập nhật {t}' },
  added: { en: '{n} new', vi: '{n} sự kiện mới' },
  view: { en: 'View', vi: 'Chế độ xem' },
  table: { en: 'Table', vi: 'Bảng' },
  grid: { en: 'Grid', vi: 'Lưới' },
  map: { en: 'Map', vi: 'Bản đồ' },
  city: { en: 'City', vi: 'Thành phố' },
  allCities: { en: 'All cities', vi: 'Mọi thành phố' },
  when: { en: 'When', vi: 'Thời gian' },
  anyTime: { en: 'Any time', vi: 'Mọi lúc' },
  tonight: { en: 'Tonight', vi: 'Tối nay' },
  weekend: { en: 'This weekend', vi: 'Cuối tuần này' },
  next7: { en: 'Next 7 days', vi: '7 ngày tới' },
  month: { en: 'This month', vi: 'Tháng này' },
  genre: { en: 'Genre', vi: 'Thể loại' },
  allGenres: { en: 'Every genre', vi: 'Mọi thể loại' },
  kind: { en: 'Night', vi: 'Kiểu đêm' },
  anyKind: { en: 'Any night', vi: 'Mọi kiểu' },
  free: { en: 'Free', vi: 'Miễn phí' },
  within5: { en: 'Under 5 km', vi: 'Dưới 5 km' },
  search: { en: 'Search events', vi: 'Tìm sự kiện' },
  searchPh: { en: 'Events, artists, venues…', vi: 'Sự kiện, nghệ sĩ, địa điểm…' },
  placePh: { en: 'Search places, areas…', vi: 'Tìm địa điểm, khu vực…' },
  place: { en: 'Search places', vi: 'Tìm địa điểm' },
  clear: { en: 'Clear filters', vi: 'Bỏ lọc' },
  empty: { en: 'Nothing matches', vi: 'Không có sự kiện nào khớp' },
  more: { en: 'Load more', vi: 'Tải thêm' },
  colDate: { en: 'Date', vi: 'Ngày' },
  colTime: { en: 'Time', vi: 'Giờ' },
  colEvent: { en: 'Event', vi: 'Sự kiện' },
  colVenue: { en: 'Venue', vi: 'Địa điểm' },
  colCity: { en: 'City', vi: 'Thành phố' },
  colPrice: { en: 'Price', vi: 'Giá' },
  colInterest: { en: 'Interested', vi: 'Quan tâm' },
  colStatus: { en: 'Status', vi: 'Trạng thái' },
  sortBy: { en: 'Sort by {c}', vi: 'Sắp xếp theo {c}' },
  stSold: { en: 'Sold out', vi: 'Hết vé' },
  stTonight: { en: 'Tonight', vi: 'Tối nay' },
  stFree: { en: 'Free', vi: 'Miễn phí' },
  stOn: { en: 'On sale', vi: 'Còn vé' },
  mapLabel: { en: 'Event map', vi: 'Bản đồ sự kiện' },
  mapSearch: { en: 'Search this area', vi: 'Tìm trong khu vực này' },
  mapMore: { en: '{n} of {t} · zoom in', vi: '{n}/{t} · phóng to thêm' },
  mapEmpty: { en: 'No events in this area', vi: 'Không có sự kiện trong khu vực này' },
  mapFailed: { en: 'The map could not load', vi: 'Không tải được bản đồ' },
  zoomIn: { en: 'Zoom in', vi: 'Phóng to' },
  zoomOut: { en: 'Zoom out', vi: 'Thu nhỏ' },
  locate: { en: 'My location', vi: 'Vị trí của tôi' },
  locateFail: { en: 'Could not find your location', vi: 'Không lấy được vị trí của bạn' },
  you: { en: 'You are here', vi: 'Vị trí của bạn' },
  details: { en: 'See details', vi: 'Xem chi tiết' },
  close: { en: 'Close', vi: 'Đóng' },
  fromPrice: { en: 'from {p}', vi: 'từ {p}' },
} satisfies Dict;
