/** The app's text (Main, App-*, Profile-Fan-App boards); English from the legacy app where it had the line. */
import type { Dict } from '../copy';

export const APP = {
  appName: { en: 'FeestFinder app', vi: 'Ứng dụng FeestFinder' },
  mainNav: { en: 'Main navigation', vi: 'Điều hướng chính' },
  tabExplore: { en: 'Explore', vi: 'Khám phá' },
  tabMap: { en: 'Map', vi: 'Bản đồ' },
  tabSaved: { en: 'Saved', vi: 'Đã lưu' },
  tabTickets: { en: 'Tickets', vi: 'Vé' },
  tabMe: { en: 'Me', vi: 'Tôi' },
  back: { en: 'Back', vi: 'Quay lại' },
  close: { en: 'Close', vi: 'Đóng' },
  search: { en: 'Search', vi: 'Tìm kiếm' },
  searchPh: { en: 'Search events, artists, venues…', vi: 'Tìm sự kiện, nghệ sĩ, địa điểm…' },
  searchGo: { en: 'Search', vi: 'Tìm' },
  notifications: { en: 'Notifications', vi: 'Thông báo' },
  notificationsNew: { en: 'Notifications, {n} new', vi: 'Thông báo, {n} mới' },
  city: { en: 'City', vi: 'Thành phố' },
  soon: { en: 'Coming soon', vi: 'Sắp có' },
  // explore
  tonight: { en: 'Tonight', vi: 'Tối nay' },
  weekend: { en: 'This weekend', vi: 'Cuối tuần này' },
  next7: { en: 'Next 7 days', vi: '7 ngày tới' },
  month: { en: 'This month', vi: 'Tháng này' },
  whatsOn: { en: "what's on?", vi: 'có gì chơi?' },
  timeMenu: { en: 'When', vi: 'Thời gian' },
  allGenres: { en: 'All', vi: 'Tất cả' },
  genres: { en: 'Genres', vi: 'Thể loại' },
  nearYou: { en: 'Near you · {n}', vi: 'Gần bạn · {n}' },
  soonest: { en: 'Soonest · {n}', vi: 'Sớm nhất · {n}' },
  seeMap: { en: 'See the map', vi: 'Xem bản đồ' },
  emptyTitle: { en: 'Nothing matches yet', vi: 'Chưa có sự kiện phù hợp' },
  emptyBody: { en: 'Try a longer time or fewer filters.', vi: 'Thử khoảng thời gian dài hơn hoặc bỏ bớt bộ lọc.' },
  reset: { en: 'Clear filters', vi: 'Xoá bộ lọc' },
  more: { en: 'Load more', vi: 'Tải thêm' },
  nEvents: { en: '{n} events', vi: '{n} sự kiện' },
  free: { en: 'Free', vi: 'Miễn phí' },
  featured: { en: 'Featured', vi: 'Nổi bật' },
  saveEvent: { en: 'Save event', vi: 'Lưu sự kiện' },
  kmAway: { en: '{d} km', vi: '{d} km' },
  // onboarding
  skip: { en: 'Skip', vi: 'Bỏ qua' },
  obTitle: { en: "What's on around you?", vi: 'Có gì quanh bạn?' },
  obBody: { en: 'Pick what you like; FeestFinder sorts the nearest events for you.', vi: 'Chọn gu của bạn, FeestFinder lọc sẵn sự kiện gần nhất.' },
  obLike: { en: 'What are you into? · pick several', vi: 'Bạn thích gì? · chọn nhiều' },
  obCount: { en: '{n} events this week', vi: '{n} sự kiện tuần này' },
  obLocate: { en: 'Use my location', vi: 'Dùng vị trí của tôi' },
  obPickCity: { en: 'Pick another city', vi: 'Chọn thành phố khác' },
  obNoLocation: { en: 'Could not get your location: pick a city', vi: 'Không lấy được vị trí: hãy chọn thành phố' },
  obPrivacy: { en: 'Your location stays on this device.', vi: 'Vị trí chỉ lưu trên thiết bị này.' },
  // event
  share: { en: 'Share', vi: 'Chia sẻ' },
  addCalendar: { en: 'Add to calendar', vi: 'Thêm lịch' },
  directions: { en: 'Directions', vi: 'Chỉ đường' },
  verifiedOrg: { en: 'Verified organiser', vi: 'Nhà tổ chức đã xác minh' },
  orgLabel: { en: 'Organiser', vi: 'Nhà tổ chức' },
  fromOrg: { en: 'From the organiser', vi: 'Từ ban tổ chức' },
  buy: { en: 'Buy tickets', vi: 'Mua vé' },
  daysLeft: { en: '{n} days to go', vi: 'Còn {n} ngày' },
  fromPrice: { en: 'from {p}', vi: 'từ {p}' },
  freeEntry: { en: 'Free entry', vi: 'Vào cửa tự do' },
  ended: { en: 'Ended', vi: 'Đã kết thúc' },
  notFound: { en: 'This event is not here', vi: 'Không tìm thấy sự kiện' },
  toExplore: { en: 'Back to Explore', vi: 'Về Khám phá' },
  // signed out
  signIn: { en: 'Log in', vi: 'Đăng nhập' },
  gateSaved: { en: 'Log in to keep events here', vi: 'Đăng nhập để lưu sự kiện ở đây' },
  gateTickets: { en: 'Log in to see your tickets', vi: 'Đăng nhập để xem vé của bạn' },
  gateMe: { en: 'Log in for your passport, alerts and settings', vi: 'Đăng nhập để có hộ chiếu, cảnh báo và cài đặt' },
  // saved
  savedTitle: { en: 'Saved', vi: 'Đã lưu' },
  savedAll: { en: 'All', vi: 'Tất cả' },
  savedEmpty: { en: 'No saved events', vi: 'Chưa lưu sự kiện nào' },
  savedEmptyBody: { en: 'Tap the heart on any event to keep it here.', vi: 'Bấm trái tim trên sự kiện để lưu lại đây.' },
  collections: { en: 'Collections', vi: 'Bộ sưu tập' },
  colPublic: { en: 'Public link', vi: 'Link công khai' },
  colPublicOn: { en: 'Public link on', vi: 'Đã bật link công khai' },
  colPublicOff: { en: 'Public link off', vi: 'Đã tắt link công khai' },
  colEmpty: { en: 'Nothing in this collection yet', vi: 'Bộ sưu tập này chưa có gì' },
  colDelete: { en: 'Delete collection', vi: 'Xoá bộ sưu tập' },
  colDeleted: { en: 'Collection deleted', vi: 'Đã xoá bộ sưu tập' },
  copyLink: { en: 'Copy link', vi: 'Chép link' },
  linkCopied: { en: 'Link copied', vi: 'Đã chép liên kết' },
  past: { en: 'Past', vi: 'Đã qua' },
  // tickets
  ticketsTitle: { en: 'My tickets', vi: 'Vé của tôi' },
  ticketsFilter: { en: 'Which tickets', vi: 'Lọc vé' },
  upcoming: { en: 'Upcoming', vi: 'Sắp tới' },
  ticketsEmpty: { en: 'No tickets yet', vi: 'Chưa có vé nào' },
  ticketsEmptyBody: { en: 'Tickets you buy land here with a QR code.', vi: 'Vé bạn mua sẽ nằm ở đây kèm mã QR.' },
  ticketN: { en: 'Ticket {i} / {n}', vi: 'Vé {i} / {n}' },
  showTicket: { en: 'Ticket {i}', vi: 'Vé {i}' },
  tier: { en: 'Tier', vi: 'Hạng vé' },
  doors: { en: 'Doors', vi: 'Mở cửa' },
  code: { en: 'Code', vi: 'Mã vé' },
  qrLabel: { en: 'QR code for ticket {c}', vi: 'Mã QR của vé {c}' },
  doorsIn: { en: 'Doors in {t}', vi: 'Mở cửa sau {t}' },
  doorsDays: { en: 'Doors in {n} days', vi: 'Mở cửa sau {n} ngày' },
  doorsOpen: { en: 'Doors open', vi: 'Đã mở cửa' },
  checkedIn: { en: 'Checked in', vi: 'Đã check-in' },
  received: { en: 'Passed to you', vi: 'Được chuyển cho bạn' },
  listed: { en: 'Up for resale · {p}', vi: 'Đang pass · {p}' },
  offlineReady: { en: 'Stored on this device · scans with no signal', vi: 'Đã lưu trên máy · quét được khi mất mạng' },
  offlineNow: { en: 'Working offline · this code still scans at the gate', vi: 'Đang ngoại tuyến · mã này vẫn quét được ở cổng' },
  liveMode: { en: 'At the event', vi: 'Chế độ tại sự kiện' },
  give: { en: 'Give', vi: 'Tặng vé' },
  resell: { en: 'Resell', vi: 'Pass vé' },
  unlist: { en: 'Take down', vi: 'Gỡ pass' },
  giveTitle: { en: 'Give this ticket', vi: 'Tặng vé này' },
  sellTitle: { en: 'Pass on this ticket', vi: 'Pass vé này' },
  phone: { en: 'Their phone number', vi: 'Số điện thoại người nhận' },
  price: { en: 'Price (₫)', vi: 'Giá (₫)' },
  cap: { en: 'At most {p}', vi: 'Tối đa {p}' },
  bank: { en: 'Bank for the money', vi: 'Ngân hàng nhận tiền' },
  account: { en: 'Account number', vi: 'Số tài khoản' },
  accountName: { en: 'Account name', vi: 'Tên chủ tài khoản' },
  payee: { en: 'Paid to {b} after the event', vi: 'Tiền về {b} sau sự kiện' },
  sendGift: { en: 'Send the ticket', vi: 'Gửi vé' },
  sendSell: { en: 'List it', vi: 'Đăng pass' },
  resold: { en: 'Resold', vi: 'Vé đã pass' },
  resoldDue: { en: 'Paid out from {d}', vi: 'Tiền về từ {d}' },
  resoldPaid: { en: 'Paid out', vi: 'Đã chuyển tiền' },
  // profile
  myProfile: { en: 'My profile', vi: 'Hồ sơ của tôi' },
  settings: { en: 'Settings', vi: 'Cài đặt' },
  edit: { en: 'Edit', vi: 'Sửa' },
  editTitle: { en: 'Edit profile', vi: 'Sửa hồ sơ' },
  name: { en: 'Name', vi: 'Tên' },
  save: { en: 'Save', vi: 'Lưu' },
  saved2: { en: 'Saved', vi: 'Đã lưu' },
  went: { en: 'Went', vi: 'Đã đi' },
  going: { en: 'Going', vi: 'Sắp đi' },
  allTickets: { en: 'All tickets', vi: 'Tất cả vé' },
  nTickets: { en: '{n} tickets', vi: '{n} vé' },
  doorsAt: { en: 'doors {t}', vi: 'mở cửa {t}' },
  passport: { en: 'Raver passport', vi: 'Hộ chiếu lễ hội' },
  passportLine: { en: '{n} nights · {g} genres · {c} cities', vi: '{n} đêm · {g} thể loại · {c} thành phố' },
  stamps: { en: '{n} stamps', vi: '{n} dấu' },
  noStamps: { en: 'No stamps yet: a ticket scanned at the door adds one.', vi: 'Chưa có con dấu: vé được quét ở cổng sẽ thêm một dấu.' },
  seeAll: { en: 'See all {n}', vi: 'Xem thêm {n}' },
  showLess: { en: 'Show less', vi: 'Thu gọn' },
  yourSound: { en: 'Your sound', vi: 'Gu của bạn' },
  byNights: { en: 'by nights out', vi: 'theo sự kiện đã đi' },
  followingTitle: { en: 'Following', vi: 'Đang theo dõi' },
  allN: { en: 'All {n}', vi: 'Tất cả {n}' },
  artistRole: { en: 'Artist', vi: 'Nghệ sĩ' },
  orgNext: { en: 'Organiser · next {d}', vi: 'Nhà tổ chức · tiếp theo {d}' },
  orgNone: { en: 'Organiser · nothing new yet', vi: 'Nhà tổ chức · chưa có lịch mới' },
  alerts: { en: 'Smart Alerts', vi: 'Cảnh báo thông minh' },
  alertsSub: { en: 'Cities, styles, artists and price', vi: 'Thành phố, phong cách, nghệ sĩ và giá' },
  notifSettings: { en: 'Notifications', vi: 'Thông báo' },
  notifSub: { en: 'What reaches you, and how', vi: 'Nhận gì, qua kênh nào' },
  language: { en: 'Language', vi: 'Ngôn ngữ' },
  signOut: { en: 'Log out', vi: 'Đăng xuất' },
  wrapped: { en: 'Wrapped {y}', vi: 'Wrapped {y}' },
  wrNights: { en: 'nights out', vi: 'đêm đi chơi' },
  wrGenre: { en: 'Your sound', vi: 'Thể loại của bạn' },
  wrArtist: { en: 'Seen most', vi: 'Gặp nhiều nhất' },
  wrVenue: { en: 'Your spot', vi: 'Chỗ quen' },
  wrTimes: { en: '{n} times', vi: '{n} lần' },
  wrGave: { en: 'You gave back', vi: 'Bạn đã góp' },
  wrPosts: { en: 'posts', vi: 'bài viết' },
  wrHelpful: { en: 'helpful votes', vi: 'lượt hữu ích' },
  wrBrought: { en: 'people brought', vi: 'người tới qua link' },
  wrPassed: { en: 'tickets passed on', vi: 'vé đã nhường' },
  wrEmpty: { en: 'No nights in {y} yet', vi: 'Chưa có đêm nào trong {y}' },
  wrShare: { en: 'Share story', vi: 'Chia sẻ story' },
  storySaved: { en: 'Story image saved', vi: 'Đã lưu ảnh story' },
  // checkout
  checkoutTitle: { en: 'Confirm your order', vi: 'Xác nhận đơn hàng' },
  gateCheckout: { en: 'Log in to buy tickets', vi: 'Đăng nhập để mua vé' },
  quantity: { en: 'Tickets', vi: 'Số lượng vé' },
  qtyDec: { en: 'One fewer', vi: 'Bớt một vé' },
  qtyInc: { en: 'One more', vi: 'Thêm một vé' },
  promo: { en: 'Promo code', vi: 'Mã giảm giá' },
  apply: { en: 'Apply', vi: 'Áp dụng' },
  total: { en: 'Total', vi: 'Tổng cộng' },
  payBy: { en: 'Bank transfer (VietQR)', vi: 'Chuyển khoản VietQR' },
  payNow: { en: 'Pay {p}', vi: 'Thanh toán {p}' },
  resaleTicket: { en: 'Resale ticket', vi: 'Vé pass' },
  transferTitle: { en: 'Transfer to get your tickets', vi: 'Chuyển khoản để nhận vé' },
  transferQr: { en: 'VietQR for {p}', vi: 'Mã VietQR {p}' },
  bankName: { en: 'Bank', vi: 'Ngân hàng' },
  accountNo: { en: 'Account', vi: 'Số tài khoản' },
  holder: { en: 'Account name', vi: 'Chủ tài khoản' },
  amount: { en: 'Amount', vi: 'Số tiền' },
  reference: { en: 'Transfer note', vi: 'Nội dung' },
  heldFor: { en: 'Held for you until {t}', vi: 'Giữ chỗ cho bạn đến {t}' },
  waiting: { en: 'Waiting for the transfer…', vi: 'Đang chờ tiền về…' },
  cancelOrder: { en: 'Cancel order', vi: 'Huỷ đơn' },
  cancelled: { en: 'Order cancelled', vi: 'Đã huỷ đơn' },
  ticketsIn: { en: 'Tickets are in My tickets', vi: 'Vé đã vào mục Vé của tôi' },
  noTiers: { en: 'Nothing on sale here right now', vi: 'Hiện không có vé để bán' },
  refund: { en: 'Refunds', vi: 'Hoàn vé' },
  // map
  mapLabel: { en: 'Events around you', vi: 'Bản đồ sự kiện quanh bạn' },
  placePh: { en: 'Search places, areas…', vi: 'Tìm địa điểm, khu vực…' },
  place: { en: 'Search places', vi: 'Tìm địa điểm' },
  mapSearch: { en: 'Search this area', vi: 'Tìm trong khu vực này' },
  mapMore: { en: '{n} of {t} · zoom in', vi: '{n}/{t} · phóng to thêm' },
  mapEmpty: { en: 'No events in this area', vi: 'Không có sự kiện trong khu vực này' },
  mapFailed: { en: 'The map could not load', vi: 'Không tải được bản đồ' },
  locate: { en: 'My location', vi: 'Về vị trí của tôi' },
  locateFail: { en: 'Could not find your location', vi: 'Không lấy được vị trí của bạn' },
  asList: { en: 'List', vi: 'Danh sách' },
  asMap: { en: 'Map', vi: 'Bản đồ' },
  view: { en: 'View', vi: 'Chế độ xem' },
  anyTime: { en: 'Any time', vi: 'Mọi lúc' },
  open: { en: 'Open', vi: 'Mở' },
  results: { en: 'Results for “{q}”', vi: 'Kết quả cho “{q}”' },
  clearSearch: { en: 'Clear search', vi: 'Bỏ tìm' },
} satisfies Dict;
