/** The home page's text. */
import type { Dict } from '../../copy';

export const HOME = {
  city: { en: 'City', vi: 'Thành phố' },
  soon: { en: 'Soon', vi: 'Sắp có' },
  when: { en: 'When', vi: 'Thời gian' },
  t_tonight: { en: 'Tonight', vi: 'Tối nay' },
  t_weekend: { en: 'This weekend', vi: 'Cuối tuần này' },
  t_7days: { en: 'Next 7 days', vi: '7 ngày tới' },
  t_month: { en: 'This month', vi: 'Tháng này' },
  tl_tonight: { en: 'tonight', vi: 'tối nay' },
  tl_weekend: { en: 'this weekend', vi: 'cuối tuần này' },
  tl_7days: { en: 'in the next 7 days', vi: '7 ngày tới' },
  tl_month: { en: 'this month', vi: 'tháng này' },
  whatsOn: { en: '— what’s on?', vi: 'có gì chơi?' },
  search: { en: 'Search events', vi: 'Tìm sự kiện' },
  searchPh: { en: 'Events, artists, venues…', vi: 'Sự kiện, nghệ sĩ, địa điểm…' },
  searchGo: { en: 'Search', vi: 'Tìm' },
  countLine: { en: '{n} events {t}', vi: '{n} sự kiện {t}' },
  sort: { en: 'Sort', vi: 'Sắp xếp' },
  s_date: { en: 'Soonest', vi: 'Gần nhất' },
  s_hype: { en: 'Most interest', vi: 'Được quan tâm' },
  s_price: { en: 'Cheapest first', vi: 'Giá thấp trước' },
  genres: { en: 'Genres', vi: 'Thể loại' },
  all: { en: 'All', vi: 'Tất cả' },
  more: { en: 'Show more', vi: 'Xem thêm' },
  emptyTitle: { en: 'Nothing matches yet', vi: 'Chưa có sự kiện phù hợp' },
  emptyBody: { en: 'Widen the dates or clear the genre.', vi: 'Thử mở rộng thời gian hoặc bỏ lọc thể loại.' },
  clearGenre: { en: 'Clear', vi: 'Bỏ lọc' },
  widen: { en: 'See this month', vi: 'Xem cả tháng' },
  featured: { en: 'Featured', vi: 'Nổi bật' },
  featuredLabel: { en: 'Featured: {t}', vi: 'Nổi bật: {t}' },
  free: { en: 'Free', vi: 'Miễn phí' },
  fromPrice: { en: 'from {p}', vi: 'từ {p}' },
  aroundYou: { en: 'Around you', vi: 'Quanh bạn' },
  nearTonight: { en: 'Nearby, tonight', vi: 'Gần đây, tối nay' },
  openMap: { en: 'Open the map', vi: 'Mở bản đồ' },
  ad: { en: 'Ad', vi: 'Quảng cáo' },
  adHide: { en: 'Hide this ad', vi: 'Ẩn quảng cáo' },
  faq: { en: 'Questions', vi: 'Câu hỏi thường gặp' },
  q1: { en: 'What is FeestFinder?', vi: 'FeestFinder là gì?' },
  a1: {
    en: 'One place to see what is on tonight: festivals, live shows and night markets. Every listing is checked before it goes live.',
    vi: 'Một nơi để biết tối nay có gì: lễ hội, show nhạc sống và chợ đêm. Mọi tin đều được kiểm tra trước khi lên sóng.',
  },
  q2: { en: 'Who sells the tickets?', vi: 'Ai bán vé?' },
  a2: {
    en: 'The organiser, or FeestFinder’s own checkout for the events it sells. FeestFinder adds no booking fee.',
    vi: 'Nhà tổ chức, hoặc FeestFinder với các sự kiện bán vé tại đây. FeestFinder không thu thêm phí đặt vé.',
  },
  q3: { en: 'Is listing an event free?', vi: 'Đăng sự kiện có mất phí không?' },
  a3: {
    en: 'Publishing is free. Get verified once and your events keep the badge, with ticket clicks and saves in your dashboard.',
    vi: 'Đăng tin miễn phí. Xác minh một lần là sự kiện của bạn giữ nhãn đã xác minh, kèm lượt bấm mua vé và lượt lưu trong bảng điều khiển.',
  },
  q4: { en: 'Something is wrong on a listing', vi: 'Tin đăng có thông tin sai' },
  a4: {
    en: 'Use “Report this listing” at the bottom of the event page, or write to hello@feestfinder.com. We usually correct it the same day.',
    vi: 'Bấm “Báo cáo tin này” cuối trang sự kiện, hoặc gửi về hello@feestfinder.com. Thường sửa trong ngày.',
  },
} satisfies Dict;
