/** Console's text (Console-Moderation and Console-Insights boards, and the undrawn tabs). */
import type { Dict } from '../copy';

export const CONSOLE = {
  console: { en: 'Console', vi: 'Console' },
  title: { en: 'FeestFinder Console', vi: 'FeestFinder Console' },
  search: { en: 'Search listings, organisers, codes…', vi: 'Tìm tin, nhà tổ chức, mã…' },
  searchLabel: { en: 'Search the Console', vi: 'Tìm trong Console' },
  tabQueue: { en: 'Moderation', vi: 'Kiểm duyệt' },
  tabVerify: { en: 'Organiser verification', vi: 'Xác minh nhà tổ chức' },
  tabReports: { en: 'Reports', vi: 'Báo cáo' },
  tabFeatured: { en: 'Featured shelves', vi: 'Kệ nổi bật' },
  tabInsights: { en: 'Numbers', vi: 'Số liệu' },
  tabAudit: { en: 'Audit log', vi: 'Nhật ký' },
  gate: { en: 'Log in to the Console', vi: 'Đăng nhập Console' },
  signIn: { en: 'Log in with Google', vi: 'Đăng nhập bằng Google' },
  notAdmin: { en: 'This account has no access to the Console', vi: 'Tài khoản này không vào được Console' },
  needsGoogle: { en: 'The Console opens with a Google sign-in', vi: 'Console chỉ mở khi đăng nhập bằng Google' },
  signOut: { en: 'Log out', vi: 'Đăng xuất' },
  viewAs: { en: 'View as', vi: 'Xem dưới' },
  viewingAs: { en: 'Viewing as {n} · read-only', vi: 'Đang xem dưới {n} · chỉ đọc' },
  viewAsExit: { en: 'Exit', vi: 'Thoát' },
  account: { en: 'Account', vi: 'Tài khoản' },
  // queue
  queue: { en: 'Queue', vi: 'Hàng chờ' },
  queueLine: { en: '{n} waiting · {d} decided today', vi: '{n} chờ · {d} đã xử lý hôm nay' },
  fAll: { en: 'All', vi: 'Tất cả' },
  fBreach: { en: 'Past the promise', vi: 'Sắp quá mốc' },
  fFlagged: { en: 'Flagged', vi: 'Bị gắn cờ' },
  fAppeals: { en: 'Appeals', vi: 'Khiếu nại' },
  flagged: { en: 'Flagged', vi: 'Gắn cờ' },
  emptyFilter: { en: 'Nothing left here', vi: 'Không còn tin trong mục này' },
  emptyHint: { en: 'Pick All to see the whole queue.', vi: 'Chọn Tất cả để xem cả hàng chờ.' },
  emptyQueue: { en: 'The queue is empty', vi: 'Hàng chờ trống' },
  submittedAgo: { en: '{g} · submitted {a} ago', vi: '{g} · gửi {a} trước' },
  verified: { en: 'Verified', vi: 'Đã xác minh' },
  unverified: { en: 'Not verified', vi: 'Chưa xác minh' },
  newOrg: { en: 'First listing', vi: 'Tin đầu tiên' },
  reject: { en: 'Reject', vi: 'Từ chối' },
  rejectHead: { en: 'Reason for rejecting', vi: 'Lý do từ chối' },
  fix: { en: 'Request changes', vi: 'Yêu cầu sửa' },
  fixHead: { en: 'Send to the organiser', vi: 'Gửi nhà tổ chức' },
  approve: { en: 'Approve', vi: 'Duyệt' },
  approveN: { en: 'Approve {n}', vi: 'Duyệt {n} tin' },
  selected: { en: '{n} selected', vi: 'Đã chọn {n}' },
  selectRow: { en: 'Select {t}', vi: 'Chọn {t}' },
  clear: { en: 'Clear', vi: 'Bỏ chọn' },
  didApprove: { en: 'Approved', vi: 'Đã duyệt' },
  didReject: { en: 'Rejected', vi: 'Đã từ chối' },
  didFix: { en: 'Changes requested', vi: 'Đã yêu cầu sửa' },
  undo: { en: 'Undo', vi: 'Hoàn tác' },
  inFeed: { en: 'In the feed', vi: 'Hiện trong feed' },
  checks: { en: 'Automatic checks · {p} / {n} pass', vi: 'Kiểm tra tự động · {p} / {n} đạt' },
  checksPass: { en: '{n} pass', vi: '{n} mục đạt' },
  review: { en: 'Review', vi: 'Xem lại' },
  pass: { en: 'Pass', vi: 'Đạt' },
  kDate: { en: 'Date', vi: 'Ngày' },
  kVenue: { en: 'Venue', vi: 'Địa điểm' },
  kPrice: { en: 'Price', vi: 'Giá' },
  kAge: { en: 'Age', vi: 'Độ tuổi' },
  allAges: { en: 'All ages', vi: 'Mọi lứa tuổi' },
  free: { en: 'Free', vi: 'Miễn phí' },
  thread: { en: 'Message the organiser', vi: 'Nhắn nhà tổ chức' },
  threadPh: { en: 'What should they change?', vi: 'Họ cần sửa gì?' },
  send: { en: 'Send', vi: 'Gửi' },
  openPage: { en: 'Open the page', vi: 'Mở trang' },
  shortcuts: { en: 'j / k move · a approves', vi: 'j / k chuyển tin · a duyệt' },
  // appeals
  appealReason: { en: 'Rejected for: {r}', vi: 'Bị từ chối vì: {r}' },
  appealReply: { en: 'The organiser says', vi: 'Nhà tổ chức phản hồi' },
  appealWaiting: { en: 'Waiting for the organiser · closes in {d} days', vi: 'Chờ nhà tổ chức · còn {d} ngày' },
  overturn: { en: 'Overturn and publish', vi: 'Lật lại và đăng' },
  uphold: { en: 'Uphold', vi: 'Giữ quyết định' },
  noAppeals: { en: 'No open appeals', vi: 'Không có khiếu nại' },
  // verification
  vAll: { en: 'All', vi: 'Tất cả' },
  vPending: { en: 'Pending', vi: 'Chờ xác minh' },
  vVerified: { en: 'Verified', vi: 'Đã xác minh' },
  vFlagged: { en: 'Flagged', vi: 'Gắn cờ' },
  docId: { en: 'ID document', vi: 'Giấy tờ tuỳ thân' },
  docTax: { en: 'Tax registration', vi: 'Đăng ký thuế' },
  docBank: { en: 'Bank statement', vi: 'Sao kê ngân hàng' },
  bankOk: { en: 'Payout account checked', vi: 'Tài khoản nhận tiền đã kiểm' },
  verify: { en: 'Verify', vi: 'Xác minh' },
  revoke: { en: 'Revoke', vi: 'Thu hồi' },
  flag: { en: 'Flag', vi: 'Gắn cờ' },
  orgLine: { en: '{e} events · {l} live · {r} in review', vi: '{e} sự kiện · {l} đang đăng · {r} chờ duyệt' },
  strikes: { en: '{n} / 3 warnings', vi: '{n} / 3 cảnh báo' },
  suspended: { en: 'Suspended', vi: 'Tạm dừng' },
  noOrgs: { en: 'No organisers here', vi: 'Không có nhà tổ chức nào' },
  // reports
  reports30: { en: 'Last 30 days', vi: '30 ngày qua' },
  reporters: { en: '{n} people', vi: '{n} người' },
  heldFromFeed: { en: 'Held from the feed', vi: 'Đang ẩn khỏi feed' },
  dismiss: { en: 'Dismiss', vi: 'Bỏ qua' },
  warn: { en: 'Warn organiser', vi: 'Cảnh cáo' },
  takeDown: { en: 'Take down', vi: 'Hạ tin' },
  takeDownAsk: { en: 'Take down {t}?', vi: 'Hạ tin {t}?' },
  noReports: { en: 'No open reports', vi: 'Không có báo cáo nào' },
  // featured
  shelves: { en: 'Shelves', vi: 'Kệ' },
  shelfNew: { en: 'New shelf', vi: 'Kệ mới' },
  shelfName: { en: 'Name', vi: 'Tên kệ' },
  shelfCreate: { en: 'Create', vi: 'Tạo' },
  shelfOn: { en: 'Show {n}', vi: 'Hiện {n}' },
  shelfFrom: { en: 'From', vi: 'Từ' },
  shelfTo: { en: 'To', vi: 'Đến' },
  shelfItems: { en: '{n} listings', vi: '{n} tin' },
  shelfAdd: { en: 'Add a live listing', vi: 'Thêm tin đang đăng' },
  shelfAddPh: { en: 'Listing name', vi: 'Tên tin' },
  shelfRemove: { en: 'Remove {t}', vi: 'Bỏ {t}' },
  up: { en: 'Move {t} up', vi: 'Đưa {t} lên' },
  boosts: { en: 'Boost requests', vi: 'Yêu cầu đẩy tin' },
  boostDone: { en: 'Featured', vi: 'Đã đẩy' },
  boostDecline: { en: 'Decline', vi: 'Từ chối' },
  boostOpen: { en: 'Waiting', vi: 'Đang chờ' },
  boostDeclined: { en: 'Declined', vi: 'Đã từ chối' },
  noBoosts: { en: 'No boost requests', vi: 'Chưa có yêu cầu đẩy tin' },
  ads: { en: 'Ads & partners', vi: 'Quảng cáo & đối tác' },
  adInquiries: { en: 'Enquiries', vi: 'Yêu cầu mới' },
  adCampaigns: { en: 'Campaigns', vi: 'Chiến dịch' },
  adApprove: { en: 'Create campaign', vi: 'Tạo chiến dịch' },
  adDecline: { en: 'Decline', vi: 'Từ chối' },
  adActive: { en: 'Run {b}', vi: 'Chạy {b}' },
  adLine: { en: '{i} impressions · {c} clicks · {p} spent', vi: '{i} lượt hiển thị · {c} lượt bấm · đã chi {p}' },
  rates: { en: 'CPM rates', vi: 'Giá CPM' },
  ratesSave: { en: 'Save rates', vi: 'Lưu giá' },
  noAds: { en: 'Nothing waiting', vi: 'Không có gì đang chờ' },
  // insights
  kLive: { en: 'Live listings', vi: 'Sự kiện đang đăng' },
  kLiveNew: { en: '+{n} this week', vi: '+{n} tuần này' },
  kUsers: { en: 'New accounts', vi: 'Người dùng mới' },
  kClicks: { en: 'Ticket clicks', vi: 'Bấm mua vé' },
  kPromise: { en: 'Decided within {h} hours', vi: 'Duyệt trong mốc {h} giờ' },
  vsPrev: { en: '{d}% vs the week before', vi: '{d}% so với tuần trước' },
  ptsPrev: { en: '{d} points vs the week before', vi: '{d} điểm so với tuần trước' },
  noPrev: { en: 'Nothing the week before', vi: 'Tuần trước chưa có' },
  weekly: { en: 'New listings by genre · 8 weeks', vi: 'Sự kiện mới theo thể loại · 8 tuần' },
  areas: { en: 'Areas with the most listings', vi: 'Khu vực nhiều sự kiện' },
  recentAudit: { en: 'Recent log', vi: 'Nhật ký gần đây' },
  chainOk: { en: 'Hash chain intact', vi: 'Chuỗi băm hợp lệ' },
  chainBroken: { en: 'Hash chain broken', vi: 'Chuỗi băm bị lỗi' },
  organisers: { en: 'Organisers', vi: 'Nhà tổ chức' },
  people: { en: 'People', vi: 'Người dùng' },
  pAccounts: { en: 'Accounts', vi: 'Tài khoản' },
  pWeekly: { en: 'Active this week', vi: 'Hoạt động tuần này' },
  pReturn: { en: 'Came back within 7 days', vi: 'Quay lại trong 7 ngày' },
  pSaves: { en: 'Saves per person', vi: 'Lượt lưu mỗi người' },
  colOrg: { en: 'Organiser', vi: 'Nhà tổ chức' },
  colLive: { en: 'Live', vi: 'Đang đăng' },
  colViews: { en: 'Views', vi: 'Lượt xem' },
  colCtr: { en: 'Click rate', vi: 'Tỉ lệ bấm' },
  colReports: { en: 'Reports', vi: 'Báo cáo' },
  // audit
  aAll: { en: 'Everyone', vi: 'Tất cả' },
  aAdmin: { en: 'Admins', vi: 'Admin' },
  aOrganizer: { en: 'Organisers', vi: 'Nhà tổ chức' },
  aSystem: { en: 'System', vi: 'Hệ thống' },
  aCsv: { en: 'Download 30 days (CSV)', vi: 'Tải 30 ngày (CSV)' },
  aNone: { en: 'Nothing recorded', vi: 'Chưa có ghi nhận' },
  more: { en: 'Show more', vi: 'Xem thêm' },
} satisfies Dict;
